- grammars/python-console.cson
Grammar for Python console (`pycon` lexer in Pygments) and doctest.
This is basically Python code that has `>>>` or `...` at the beginning of lines.
Refs: https://github.com/github/linguist/issues/1939
Cc: @aroben
> Add highlighting for a Python console session or doctest with ">>>" and "..." at beginning of lines

- grammars/python-console.cson
This is commonly used in docs as well.
E.g.:
https://github.com/hynek/characteristic/pull/26#issuecomment-69324256
> Make python-console handle doctest filetype too

- grammars/python.cson
0777 up to Python 2.7, 0o777 in 2.6/3.0 and up. Also see [PEP-3127](https://www.python.org/dev/peps/pep-3127/) for full integer literal syntax
> Match Python 3 octal literals

- grammars/python.cson
Highlight binary literals (supported in Python 2.6/3.0 and up), e.g. `0b10101`.
> Add binary literals

- grammars/python.cson
As I have multiple versions of python installed on my system, I generally like to specify the version of python in my shebang lines. However, atom does not detect these files as python when they don't have the `.py` file extension. I have modified the first line regex to match numbers and dots immediately following the word "python".
The following will now match in addition to all other matched lines:
```python
#!/usr/bin/python3
#!/usr/bin/env python3
#!/usr/bin/env python3.4
```
> Add support for version numbers in the first line for python

- grammars/python.cson
Add highlighting support for additional :sparkles: magic :sparkles: attributes, variables, and method names. See https://docs.python.org/dev/reference/datamodel.html
> Add more magic

- settings/language-python.cson
PEP8 clearly states that 4 spaces should be used for indentation, and this
change ensures that regardless of whether the user has configured hard tabs
as their global default.
Refs #62
> Ensure soft tabs is used by default

- grammars/python.cson
- spec/python-spec.coffee
The current grammar for "meta.item-access.arguments.python" matches zero or more whitespace characters which can cause syntax highlighting to break with the examples contained in: https://github.com/atom/language-python/issues/60
Changing the match to one or more whitespace characters fixes the issue and is enforced by E211 of pep8 (whitespace before "[") so it keeps to Python syntax checking.
> Fix for issue #60, match one or more whitespace instead of zero or more

- grammars/python.cson
- spec/python-spec.coffee
This fixes #77.  The issue is that the language_variables rule was before the dotted_name rule, so it took precedence.  Thus, when the grammar tried to parse `'self.foo'`, it parsed `'self'` alone, leaving it to parse `'.foo'`, which it did strangely as `['.', 'f', 'oo']`.  Now it tries to parse it as a dotted_name first, which handles that case correctly.  This PR also includes two relevant specs.
> Fix 77: Correctly tokenize 'self.foo'.

- grammars/python.cson
- spec/python-spec.coffee
This pull request fixes an issue reported in #81:
```python
def __init__(
self,
container,
group,
codec=0,  # requests small enough that compression would be unnecessary overhead
**config
):
```
See the [fix in Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpchaigno%2Flanguage-python%2Fdeb68c308c6e3a1f49dbc295d50b5d7b61581206%2Fgrammars%2Fpython.cson&grammar_text=&code_source=from-text&code_url=&code=def+__init__%28%0D%0A++++self%2C%0D%0A++++container%2C%0D%0A++++group%2C%0D%0A++++codec%3D0%2C++%23+requests+small+enough+that+compression+would+be+unnecessary+overhead%0D%0A++++**config%0D%0A%29%3A).
> Line comments in function arguments

- grammars/python.cson
- spec/python-spec.coffee
Fixes inline SQL syntax highlighting for the following two scenarios:
```
query = """
SELECT *
FROM foo
"""
```
and
```
query = '''
SELECT *
FROM bar
'''
```
> Fix inline SQL  in Python Grammar for block strings with starting new lines

- grammars/python.cson
Added `await` keyword to `illegal_name` and `keyword.control.statement.python`
Reference issue #93
> Add await keyword for Python 3.5

- grammars/python.cson
- spec/python-spec.coffee
This looks for SQL queries which being with the `WITH` statement, which signals a Common Table Expression.
I’m confident the test case I added to the spec is not correct, but attempting to run it in Atom via View>Developer>Run Package Specs passed. I welcome any suggestions to improve the test case or pointers to make sure it’s running correctly within Atom.
Fixes #102
> Add support for CTEs in embedded SQL

- snippets/language-python.cson
If you use the pdb/ipdb snippet, an extra newline is inserted into your code. This is undesirable, and inconsistent with all other snippets (with the exception of enc/env, where it makes sense).
This PR removes the extra newlines.
> No newline after pdb/ipdb for consistency with other mid-file snippets

- snippets/language-python.cson
Added two more debuggers:
* PuDB: [fullscreen console-based debugger](https://pypi.python.org/pypi/pudb)
* rPDB: [graphical remote debugger](https://pypi.python.org/pypi/rpdb/)
> More debuggers

- snippets/language-python.cson
The python [PEP 257 states](https://www.python.org/dev/peps/pep-0257/) that for one line doc strings:
> "The docstring is a phrase ending in a period."
This PR is adding a period to the class snippet, so that is complies with PEP 257
> Fixing the class snippet by adding period to the doc string

- grammars/python.cson
- spec/python-spec.coffee
Added space regex in between she bang and start of path. Fix for #173 
None considered
Better shebang Python language detection.
#173
> add regex to support spaces in firstline shebang, add corresponding specs

- snippets/language-python.cson
Even if -*- is cosmetic and encoding: utf8 is equal to encoding= utf8 in the Python documentation the shown example is 
```
#!/usr/bin/env python
```
See:
- https://docs.python.org/3/howto/unicode.html#unicode-literals-in-python-source-code
I would use the form proposed in the doc.
It seems to me that the proposed format is more popular.
> Be compliant with the Python documentation

- snippets/language-python.cson
After reviewing a recent reddit discussion about [the most repetitive code pieces people type](https://www.reddit.com/r/Python/comments/6bjgkt/what_are_the_most_repetitive_pieces_of_code_that/), I checked the most often mentioned items against the available snippet list. The only one that stood out to me as missing was the with statement, which I add here after confirming that it works in my own snippets.
It's basically copy/pasted from the for statement snippet, and a simple change, so should hopefully be ok without tests? other snippet PRs were also merged without
Adds a with statement snippet
> Add with statement to snippets

- settings/language-python.cson
- spec/language-python-spec.coffee
* Add spec file for indentations. Modeled after https://github.com/atom/language-go/blob/master/spec/language-go-spec.coffee
* Dedent next line after some expressions (`pass|return|yield|continue|break|raise`)
None.
Better support for the Python language.
* yet another regex to run text on
* do you ever *not* want to dedent on one of `return|yield|continue|break|raise`?
* might break 3rd party python indentation packages, e.g. https://github.com/DSpeckhals/python-indent
* https://github.com/DSpeckhals/python-indent/issues/20
* https://github.com/atom/atom/issues/12742
> Indentation updates

- snippets/language-python.cson
Adds snippets for python 3 env header and set comprehension.
No other designs for these were considered. These were modeled after the python env header and the list comprehension that already exit as snippets.
This minor improvement makes the snippet collection more complete and like all snippets provides easy access to perhaps frequently typed things with a few keystrokes.
A possible drawback is that with the "env3" snippet one may write "env" and accidentally scroll down to env3 with a mouse or keyboard. This seems unlikely and not a huge problem even if it does happen.
Fixes some minor annoyances.
Screenshots:
> Made some additions to the snippets

- settings/language-python.cson
- spec/language-python-spec.coffee
This PR reverts the functional changes of #204.  Unfortunately, there is no way (yet) to tell if we're in an `if` block, which can lead to multiple dedenting in the following scenario:
```python
if True:
return
else: # but typing `else:` will trigger another dedent from `decreaseIndentPattern`
```
I would argue that that is worse than having to shift-tab after a return that is not in an if statement.
/cc @kbrose
Fixes #209
> Remove patterns for decreasing next indent level

- grammars/python.cson
- spec/language-python-spec.coffee
- spec/python-spec.coffee
Add lowercase letters to hex characters inside strings.
None
Proper highlighting of lowercase hex letters such as
```python
s = '\x0a'
```
None..................?
https://github.com/atom/language-python/issues/200
Stagnant PR accomplishing same thing w/o tests: https://github.com/atom/language-python/pull/201
> Lowercase hex in str

- grammars/tree-sitter-python.cson
- package.json
⚠️ Work In Progress ⚠️
This adds an alternative Python grammar that uses [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python) for parsing instead of [first-mate](https://github.com/atom/first-mate).
> Add tree-sitter Python grammar

- grammars/python.cson
- spec/python-spec.coffee
The string formatting rules have been updated according to the two official specs, https://docs.python.org/2/library/stdtypes.html#string-formatting for the deprecated `%` style and 
https://docs.python.org/3/library/string.html#format-string-syntax for the new `{}` style.
None.
By being in line with the specs, a number of formatting-related bugs should be fixed.
* The `%` spec is a bit ambiguous (for example, what constitutes a "sequence of characters"?) so it is possible that I misinterpreted parts of it.
* While not explicitly stated in the `{}` spec, …
> Level up string formatting

- grammars/python.cson
- spec/python-spec.coffee
`'{{test}}'` does not indicate a format specifier but rather escaped curly brackets.
None.
Curly bracket escapes will be recognized in strings.
None.
Fixes #182
> Tokenize {{ and }} as escape characters

- grammars/regular expressions (python).cson
- spec/python-regex-spec.coffee
- spec/python-spec.coffee
Because there is no such thing as recursive character classes in Python.
In addition, removed the special casing of `.` from being tokenized as `constant.character.character-class.regexp` because it has no special meaning in character classes.
The edge case of having `]` as the first character in the character class is now handled correctly as a bonus.
None.
Character classes with an opening square bracket inside of them will no longer break highlighting for the rest of the file.
None.
Fixes #174
> Do not recursively match character classes

- grammars/python.cson
- spec/python-spec.coffee
* Add support for PEP-498 "f-strings", which were added in Python 3.6.  f-strings are similar to interpolation in other languages with the exception that they also support format specifiers.
* Add support for nested replacement fields in top-level format specifiers.  This change is dirty, but it works.
To reduce the complexity of the format specifier pattern, I could have used a generic `.*` pattern of some sort and not matched against the spec.
`f"{stuff}"`-style strings will be supported.  Complex format specifiers such as `{:{width}}` will also be …
> Add support for f-strings and nested replacement fields

- grammars/python.cson
- spec/python-spec.coffee
Tokenizes `yield from` as described in [PEP-380](https://www.python.org/dev/peps/pep-0380/).
None.
`yield from` will be tokenized as one expression instead of two (`yield` + `from` as in `import from`).
None.
Fixes #119
> Tokenize `yield from`

- grammars/python.cson
- spec/python-spec.coffee
This PR fixes a few deficiencies regarding lambda tokenization, such as:
* The colon marking the start of the function was incorrectly tokenized as `punctuation.definition.parameters.end.python`, most likely because the `endCaptures` block was copy/pasted from the function pattern.
* Hard-to-read (and incorrect!) parameter matching, again most likely copied from functions.
None.
Better lambda highlighting.
None.
None.
> Improve lambda tokenization

- grammars/python.cson
- spec/python-spec.coffee
There are two main changes in this PR.
1. Support async function definitions, `async def test(params):` as per [PEP-492](https://www.python.org/dev/peps/pep-0492/).  `async` is tokenized as `storage.modifier.async.python`, similarly to JavaScript.
2. Instead of having two function definition patterns, one for the full form and one for when the parameters list is missing, I have consolidated both patterns into one while retaining the invalid highlighting.  You can see an example of how this works in the specs.
None.
I believe this is the last part of …
> Tokenize async function definitions

- grammars/python.cson
- spec/python-spec.coffee
Python 3.0 introduced binary strings ([PEP-3112](https://www.python.org/dev/peps/pep-3112)), which this PR adds support for.
None.
Binary strings will be tokenized properly.
None.
None.
> Tokenize binary strings

- grammars/python.cson
- spec/python-spec.coffee
Tokenizes optional function and parameter annotations in accordance with [PEP-3107](https://www.python.org/dev/peps/pep-3107/).
I looked at the three prior attempts.
#84 did not add support for function return-value annotations
#88 did not add highlighting for annotations
#95 when I was testing it didn't appear to support function return-value annotations
Fully supports PEP-3107, which has been in effect since Python 3.0 was released.
This PR does include some minor relaxations in function definition syntax in order to more easily accommodate annotations. …
> Tokenize function and parameter annotations

- grammars/python.cson
- spec/python-spec.coffee
* Tokenize function names for function and method calls
* Tokenize objects and properties
| Before | After |
| ------- | ------ |
| ![language-python-before](https://user-images.githubusercontent.com/2766036/35310484-a70f7f24-007f-11e8-90d9-bb884e9f661b.png) | ![language-python-after](https://user-images.githubusercontent.com/2766036/35310440-65d9dfb8-007f-11e8-8df8-cab3f250c3ab.png)
Quite the difference if I do say so myself.  This brings language-python in line with other languages such as language-javascript, language-coffee-script, language-php, etc. …
> Improve tokenization

- grammars/python.cson
- spec/python-spec.coffee
My fix in #243 was causing all docstrings to be tokenized as `meta.embedded.sql`.  I fixed that by only adding that scope when SQL is detected and adding some basic docstring tests.
> Not all docstrings are SQL

- grammars/python.cson
- spec/python-spec.coffee
Capture lambda with `\b(lambda)\s?+`
Resolve #246 
#246
> fix lambda parsing issues #246

- grammars/python.cson
- spec/python-spec.coffee
Matches `lambda` via lookahead for whitespace or `:`. This resolves #246 and a problem introduced in #253 
#253 broke parsing `lambda_not.foo`. This fixes it while preserving correct tokenization for #246
> add more test cases for lambda tokenization

- grammars/python.cson
- package.json
- spec/fixtures/grammar/syntax_test_python.py
- spec/fixtures/grammar/syntax_test_python_functions.py
- spec/fixtures/grammar/syntax_test_python_lambdas.py
- spec/fixtures/grammar/syntax_test_python_typing.py
- spec/python-spec.coffee
Introduce syntax tests to improve the test coverage.  Anticipating changes for the tree-sitter migration (cc @maxbrunsfeld + @ambv), we'd benefit from having a more complete set of grammar tests to ensure compatibility.  This begins developing those test fixtures.
This introduces a few syntax fixture files and fixes a bug with missing vararg and kwarg syntax highlighting.
[atom-grammar-test](https://github.com/kevinastone/atom-grammar-test) is a test helper to allow you to provide code snippets and examples that you annotate with the desired syntax rules.  It makes it much easier to validate the grammar rules and allows parties to provide examples of missing of errant syntax highlighting.
Dependency on another package?  It's been used by several atom language grammars to date.
N/A
> Migrate to Atom-Grammar-Tests

- snippets/language-python.cson
Currently when you type in lcie to autocomplete a list comprehension if else it autocompletes it to '[value if condition else condition for value in variable]'. But it should actually be '[value if condition else value for value in variable]' since you are specifying an alternative value after the 'else' and not specifying another condition.
There are not any other reasonable ways to make this change.
The list comprehension if else auto-completion will be clearer.
None
None
> 'lcie' prefix was 'else condition' when it should have been 'else value'

- grammars/tree-sitter-python.cson
I added some missing keywords (`global`, `nonlocal`, `exec`, `del`). I changed the scope of `print` and `assert` from `keyword.control` to `keyword.other`, so that they have the same scope as `exec` and `del`. This is more consistent with the scopes in `python.cson`.
> Add missing keywords to tree-sitter-python

- grammars/regular expressions (python).cson
- spec/python-regex-spec.coffee
Add in escape rule, so we don't get false positives for groups, etc.
I could have tried finding all proper escapable characters, but that's difficult. My experiments with regex101.com indicate escaping any character will count as an escape, in some way or another (e.g., `\q` means a literal `q`).
No more leaking regex when opening parentheses are supposed to be escaped
Unicode escapes are more complicated, but I believe they are not supported at all currently. This will not break them.
Fixes https://github.com/atom/language-python/issues/259
> Escape regex properly

- settings/language-python.cson
Add a value for `foldEndPattern` in the package settings. This improves the folding behavior for dictionaries, lists, and functions when not using the tree-sitter parser. It folds the entire logical syntax item instead of leaving the ending character on a separate line. It also improves the use of [Hydrogen](https://atom.io/packages/Hydrogen) when the ending `}`, `)`, or `]` is on a separate line and not indented.
Many other core Atom language grammars have a `foldEndPattern`; the regex used in this PR is taken from [`language-javascript`](https://github.com/atom/language-javascript/blob/df7a049ec5b6e866b1686c561ba8d8bb7c0de0c5/settings/language-javascript.cson#L5) because of the similarity in syntax used for data structures.
The regex is `^\\s*\\}|^\\s*\\]|^\\s*\\)` in order to fold the …
> Add foldEndPattern to settings

- grammars/tree-sitter-python.cson
Scopes built in python functions as `support.function`. Textmate scoped these as `support.function.builtin.python`.
https://github.com/atom/language-python/issues/286 reported that `print` is no longer scoped as `keyword.other`. Textmate always scoped `print` and `exec` as `keyword.other` even when they were used as a function. In Python 3 these keywords were removed and `print` and `exec` are built in functions.
This PR fixes https://github.com/atom/language-python/issues/286 by scoping all built in functions as `support.function`.
Function list taken …
> Scope built in functions as support.function

- snippets/language-python.cson
Fixes #261 
Fixes #154
I removed this snippet:
```
'.source.python:not(.string)':
'self':
'prefix': '.'
'body': 'self.'
```
-->
I considered retooling the snippet so that there was still a way for 'self' to be auto-populated in some fashion, but ultimately reasoned that the time saved from not having to type four characters is not worth the time lost having it populated accidentally.
People will be more likely to use Atom to write their Python scrips.  With the current code, 'self' is injected at almost every use of '.'  Which, as you can imagine, becomes burdensome, especially since it also applies to text written in comments.
Some people may be using this feature and they may be annoyed to see it go.
I personally believe that more people would welcome the change than be irritated by the …
> Please remove snippet config for 'self'

- snippets/language-python.cson
Added a newline after the docstring of the new class snippet. This is required to respect E301.
None
Valid codestyle
None
-
> Fix codestyle E301 in class snippet

- grammars/tree-sitter-python.cson
This PR fixes #290 which reports that the Tree-Sitter Python grammar does not fold `elif` and `else` correctly.  The fix is to update `tree-sitter-python.cson` to be a little more explicit about the nodes that cause `if_statement` folding to end.
**Before**
**After**
None.
`elif` and `else` blocks fold as expected.
None?
Fixes #290
> Fix code folding for 'elif' and 'else' statements

- grammars/tree-sitter-python.cson
I add shebang lines atop all my Python files. If I use `#!/usr/bin/python` or `#!/usr/bin/env python`, the buffer will use the Python tree-sitter grammar (instead of first-mate). However, if I use `#!/usr/bin/env python2` or `#!/usr/bin/env python3`, the tree-sitter grammar is always ignored (in favor of first-mate).
This PR updates the `firstLineRegex` field in the tree-sitter grammar to exactly match what's in the first-mate grammar. As a result, `.py` files with a `python2` or `python3` shebang now use the `tree-sitter` grammar (if tree-sitter is …
> Add support for python2/3 shebangs in tree-sitter grammar

- grammars/tree-sitter-python.cson
This PR adds the suggested changes from https://github.com/atom/language-python/pull/257 using the latest tree-sitter-python and API.
We are using:
`'binary_operator > "@"': 'keyword.operator'`
To avoid highlighting the `@` in `decorated_definition > decorator > "@"` as `keyword.operator` in f.ex.:
```python
@classmethod
def foo(*, arg1,arg2):
...
```
1. When raising exception using the `raise Exception('a')` syntax. The exception is scoped as a function call (`entity.name.function`). Should `Exception` be `support.type.exception` in this case as well?
```python
raise ValueError('A very specific bad thing happened.')
```
2. Compared to https://github.com/atom/language-python/pull/257 we are missing two functions:
`__build_class__`
`BuiltinImporter`
I used the list from …
> Add more scopes to the tree sitter grammar

- grammars/tree-sitter-python.cson
This PR tokenizes the formal function parameters in the `tree-sitter` grammar:
**Before:**  
**After:**  
I don't know if the core Atom team would prefer to use a different scope to tokenize these formal function parameters. However, the `variable.parameter.function` scope is already used to tokenize keyword arguments in the tree-sitter grammar, so I don't think there's any inconsistency here.
Better highlighting for the formal function parameters in Python files matched by the tree-sitter grammar. This matches the highlighting in the existing first-mate …
> Tokenize formal function parameters in tree-sitter grammar

- grammars/tree-sitter-python.cson
This PR tokenizes the names of subclasses listed within class definitions, for Python files matched by the tree-sitter grammar.
**Before:**  
**After:**  
I don't know if the Atom team desires to tokenize these subclass names differently; I figured `entity.other.inherited-class` was the most appropriate scope, as it's based on the same scope from the first-mate grammar.
Syntax highlighting that is more familiar to longtime users of the Python first-mate grammar.
Perhaps some might prefer different colors be used for the subclass names, though I personalli …
> Tokenize subclass list names in tree-sitter grammar

- grammars/tree-sitter-python.cson
The changes introduced in https://github.com/atom/language-python/pull/292 made it impossible to fold an `if_statement` without an `elif_clause` and/or `else_clause`. This PR fixes this by adding back `if_statement` to the fold rules and rearranges the rules so the rule that ends with `elif_clause` and `else_clause` types take precedence.
***Before:***
***After:***
No
Can fold lonely if statements again
No
Folding part of https://github.com/atom/language-python/issues/299
/cc: @daviwil FYI
> Allow folding if statement without elif or else

- grammars/tree-sitter-python.cson
Back in https://github.com/atom/language-python/pull/297, I added highlighting for formal function parameters to the Python tree-sitter grammar. This PR follows up on that work with two additional fixes for splat parameters such as `*args` and `**kwargs`.
I could've chosen more-generic or more-specific selectors to tokenize these nodes, depending on how broad these changes are desired to be. But to avoid any potential breakages, I aimed to keep these changes narrow in scope.
**Before:**  
**After:**  
More consistent syntax highlighting for …
> Tokenize *args and **kwargs the same as other parameters (tree-sitter)

- grammars/python.cson
Added keyword async:
```
'illegal_names':
'match': '\\b(and|as|assert|break|class|continue|def|del|elif|else|except|exec|finally|for|from|global|if|import|in|is|lambda|nonlocal|not|or|pass|print|raise|return|try|while|with|yield|await|async)\\b'
'name': 'invalid.illegal.name.python'
```
- People are less likely going to use reserved names for asynchronous stuff
Code that already uses async as a variable name will be highlighted differently
> Added async (line 851)

- grammars/python.cson
- spec/python-spec.coffee
Currently, the uppercase `DELETE` is a trigger to initiate coloring for embedded SQL. That comes into conflict with the HTTP request descriptions, where `DELETE` is one of the allowed methods.
So an API-describing string like:
```python
"""
GET /endpoint
POST /endpoint
DELETE /endpoint
PATCH /endpoint
"""
```
starts getting wrong highlighting starting from the DELETE keyword.
This PR aims to cover this particular case of the occurence of `DELETE` in a string.
API descriptions in Python strings will look more appealing, and provided that servers are frequently written in Python, this is a considerable use case.
Looks a little hacky.
> Add a lookahead for DELETE to avoid mistaking HTTP strings for SQL
